SELECT 
    b.AUTHOR_ID AS AUTHOR_ID,
    a.AUTHOR_NAME AS AUTHOR_NAME,
    b.CATEGORY AS CATEGORY,
    SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM 
    BOOK b 
JOIN 
    AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN 
    BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE 
    bs.SALES_DATE LIKE '2022-01%'
GROUP BY 
    b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY 
    b.AUTHOR_ID ASC, b.CATEGORY DESC;
