-- 1. 최초 대장균 개체 찾고
WITH ECOLI_FIRST AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), 
-- 2. 2세대 찾고
ECOLI_SECOND AS (
    SELECT e.ID
    FROM ECOLI_DATA e JOIN ECOLI_FIRST f ON e.PARENT_ID = f.ID
)
-- 3. 3세대 찾음
SELECT e.ID AS ID
FROM ECOLI_DATA e JOIN ECOLI_SECOND s ON e.PARENT_ID = s.ID
ORDER BY e.ID;
