SELECT
    A.ID
    , CASE 
        WHEN PCT <= 0.25 THEN 'CRITICAL'
        WHEN PCT <= 0.5 THEN 'HIGH'
        WHEN PCT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA A
JOIN (
    SELECT 
        ID
        , PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
    FROM ECOLI_DATA
) B ON A.ID = B.ID
ORDER BY A.ID;