-- 코드를 입력하세요
SELECT
    A.APNT_NO AS APNT_NO
    , P.PT_NAME AS PT_NAME
    , A.PT_NO AS PT_NO
    , A.MCDP_CD AS MCDP_CD
    , D.DR_NAME AS DR_NAME
    , A.APNT_YMD AS APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE A.APNT_CNCL_YMD IS NULL
    AND YEAR(APNT_YMD) = 2022
    AND MONTH(APNT_YMD) = 4
    AND DAY(APNT_YMD) = 13
    AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;