WITH REVIEW_COUNTS AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TOP_REVIEWERS AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNTS
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNTS)
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (SELECT MEMBER_ID FROM TOP_REVIEWERS)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;