WITH REVIEW_COUNTS AS (
    SELECT 
        MEMBER_ID, 
        COUNT(*) AS REVIEW_COUNT -- 각 회원의 리뷰 수를 계산
    FROM 
        REST_REVIEW
    GROUP BY 
        MEMBER_ID

), REVIEWKING AS (
    SELECT 
        MEMBER_ID
    FROM 
        REVIEW_COUNTS
    WHERE 
        REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNTS) -- 최대 리뷰 수를 가진 회원 선택
)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REVIEWKING K
JOIN REST_REVIEW R ON K.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE  M ON K.MEMBER_ID = M.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;
