WITH RAREITEM AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
SELECT 
    t.ITEM_ID AS ITEM_ID
    , i.ITEM_NAME AS ITEM_NAME
    , i.RARITY AS RARITY
FROM ITEM_TREE t
JOIN RAREITEM r ON t.PARENT_ITEM_ID = r.ITEM_ID
JOIN ITEM_INFO i ON t.ITEM_ID = i.ITEM_ID
ORDER BY ITEM_ID DESC;
