SELECT
    b.TITLE AS TITLE,
    b.BOARD_ID AS BOARD_ID,
    r.REPLY_ID AS REPLY_ID,
    r.WRITER_ID AS WRITER_ID,
    r.CONTENTS AS CONTENTS,
    TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE >= DATE '2022-10-01'
  AND b.CREATED_DATE < DATE '2022-11-01'
ORDER BY r.CREATED_DATE, b.TITLE;
