SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (
    SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS ADJUSTED_LENGTH, LENGTH
    FROM FISH_INFO
) AS sub
GROUP BY FISH_TYPE
HAVING AVG(ADJUSTED_LENGTH) >= 33
ORDER BY FISH_TYPE ASC;